apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: bss-init{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: bss-init{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: bss-init{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "1.0.288-ubi8"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
      containers:
        - name: bss-init
          image: {{ .Values.docker_registry_prefix }}/bss-init:1.0.288-ubi8
          command: ["/bin/bash"]
          args: ["-c", "./run.sh"]
          env:
            - name: TM1Location
              value: "{{ .Values.common.tm1Location }}"
            - name: IBMCognosServlet
              value: "{{ .Values.common.ibmCognosServlet }}"
            - name: TM1APIPort
              value: "{{ .Values.common.tm1APIPort }}"
            - name: ENABLE_USER_IMPORT
              value: "{{ .Values.waProxy.enableUserImport }}"
            - name: ENABLE_PASTE_SPECIAL
              value: "{{ .Values.bssInit.enablePasteSpecial }}"
            - name: ENABLE_PAA
              value: "{{ .Values.bssInit.enablePAA }}"
            - name: ENABLE_EDIT_MDX_VIEW
              value: "{{ .Values.bssInit.enableEditMdxView }}"
            - name: ENABLE_INTENT_BAR
              value: "{{ .Values.bssInit.enableIntentBar }}"
            - name: WAProxyLocation
              value: "http://wa-proxy{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}:1331"
          resources:
            limits:
              cpu: "{{ .Values.bssInit.cpuLimit }}"
              memory: "{{ .Values.bssInit.memoryLimit }}"
            requests:
              cpu: "{{ .Values.bssInit.cpuRequestLimit }}"
              memory: "{{ .Values.bssInit.memoryRequestLimit }}"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.bssInit.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.bssInit.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.bssInit.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.bssInit.livenessProbeTimeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.bssInit.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.bssInit.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.bssInit.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.bssInit.readinessProbeTimeoutSeconds }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: OnFailure
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler

