apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: pa-config-secret-tls{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: pa-config-secret-tls{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: pa-config-secret-tls{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: 1.0.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
      containers:
        - name: pa-config-secret-tls
          image: {{ .Values.docker_registry_prefix }}/k8s-config:1.0.106-ubi8
          command: ["/bin/bash"]
          args: ["-c", "/opt/harmony/start.sh tls"]
          env:
            - name: PA_KUBE_TLS_CERT_EXTERNAL
              value: "{{ .Values.secrets.tlsCertExternal }}"
            - name: PA_KUBE_TLS_CERT_SECRET_NAME
              value: {{ .Values.secrets.tlsCertSecretName }}
            - name: PA_KUBE_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: PAW_INSTANCE_ID
              value: "{{ .Values.instanceIdWithinNamespace }}"
          resources:
            limits:
              cpu: {{ .Values.secrets.cpuLimit }}
              memory: {{ .Values.secrets.memoryLimit }}
            requests:
              cpu: {{ .Values.secrets.cpuRequestLimit }}
              memory: {{ .Values.secrets.memoryRequestLimit }}
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.secrets.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.secrets.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.secrets.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.secrets.livenessProbeTimeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.secrets.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.secrets.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.secrets.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.secrets.readinessProbeTimeoutSeconds }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Never
      serviceAccountName: pa-config-secret{{ .Values.instanceIdWithinNamespace }}
      terminationGracePeriodSeconds: 5
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler

