apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: mysql-data1{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: mysql-data1{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-data1{{ .Values.instanceIdWithinNamespace }}
  template:
    metadata:
      annotations:
        hook.activate.cpd.ibm.com/command: '[]'
        hook.deactivate.cpd.ibm.com/command: '[]'       
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: mysql-data1{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "2.0.170-ubi8"
        pa-cacerts-version: {{ .Values.secrets.cacertVersion }}
        pa-tls-version: {{ .Values.secrets.tlsCertVersion }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - mysql-data2
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: mysql-data1-storage
          persistentVolumeClaim:
            claimName: mysql-data1{{ .Values.instanceIdWithinNamespace }}
        - name: pa-cacerts
          emptyDir:
            medium: {{ .Values.secrets.tlsEmptyDirMedium }}
            sizeLimit: {{ .Values.secrets.tlsEmptyDirSizeLimit }}
        - name: pa-tls-cacerts
          secret:
            secretName: pa-tls-cacerts{{ .Values.instanceIdWithinNamespace }}
        - name: pa-tls-cert
          secret:
            secretName: {{ .Values.secrets.tlsCertSecretName }}{{ .Values.instanceIdWithinNamespace }}
      initContainers:
        - name: prepare-cacerts
          image: {{ .Values.docker_registry_prefix }}/k8s-config:1.0.106-ubi8
          command: ["/bin/bash"]
          args: ["-c", "/opt/harmony/start.sh capem"]
          env:
           - name: PA_KUBE_TM1_CA_CERTS
             value: /run/secrets/paw/tls-cacerts/cacerts.pem
           - name: PA_KUBE_TLS_CA_CERT
             value: /run/secrets/paw/tls-cert/{{ .Values.secrets.tlsCaCertName }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: {{ .Values.secrets.cpuLimit }}
              memory: {{ .Values.secrets.memoryLimit }}
            requests:
              cpu: {{ .Values.secrets.cpuRequestLimit }}
              memory: {{ .Values.secrets.memoryRequestLimit }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: pa-cacerts
            mountPath: /run/config
          - name: pa-tls-cacerts
            mountPath: /run/secrets/paw/tls-cacerts
          - name: pa-tls-cert
            mountPath: /run/secrets/paw/tls-cert
      containers:
        - name: pingservice
          image: {{ .Values.docker_registry_prefix }}/k8s-config:1.0.106-ubi8
          command: ["/bin/bash"]
          args: ["-c", "/opt/harmony/pingservice" ]
          ports:
            - containerPort: 31001
              protocol: TCP
          resources:
            limits:
              cpu: "{{ .Values.common.cpuLimit }}"
              memory: "{{ .Values.common.memoryLimit }}"
            requests:
              cpu: "{{ .Values.common.cpuRequestLimit }}"
              memory: "{{ .Values.common.memoryRequestLimit }}"
          env:
            - name: PINGSERVICE_PORT
              value: "31001"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 31001
            failureThreshold: {{ .Values.mysqlData.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.mysqlData.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.mysqlData.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.mysqlData.livenessProbeTimeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 31001
            failureThreshold: {{ .Values.mysqlData.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.mysqlData.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.mysqlData.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.mysqlData.readinessProbeTimeoutSeconds }}
        - name: mysql-data1-stunnel
          image: {{ .Values.docker_registry_prefix }}/mysql-cluster:2.0.170-ubi8
          command: [ "/tools/start-stunnel.sh" ]
          ports:
            - containerPort: 12201
              protocol: TCP
          resources:
            limits:
              cpu: "{{ .Values.mysqlDataStunnel.cpuLimit }}"
              memory: "{{ .Values.mysqlDataStunnel.memoryLimit }}"
            requests:
              cpu: "{{ .Values.mysqlDataStunnel.cpuRequestLimit }}"
              memory: "{{ .Values.mysqlDataStunnel.memoryRequestLimit }}"
          env:
            - name: MYSQL_INSTANCE
              value: "{{ .Values.instanceIdWithinNamespace }}"
            - name: MYSQL_DOMAIN
              value: "{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}"
            - name: STUNNEL_CLIENT_MAPPINGS
              value: "mysql-mgmt,127.0.0.1:1186,mysql-mgmt{{ .Values.instanceIdWithinNamespace }}:11186 mysql-data2,127.0.0.1:2202,mysql-data2{{ .Values.instanceIdWithinNamespace }}:12202"
            - name: STUNNEL_SERVER_CA_FILE
              value: "/run/config/cacerts.pem"
            - name: STUNNEL_SERVER_CERT_FILE
              value: "/run/secrets/paw/tls-cert/tls.crt"
            - name: STUNNEL_SERVER_KEY_FILE
              value: "/run/secrets/paw/tls-cert/tls.key"
            - name: STUNNEL_SERVER_MAPPINGS
              value: "mysql-data1,0.0.0.0:12201,127.0.0.1:2201"
            - name: STUNNEL_CLIENT_VERIFY_CHAIN
              value: "false"
            - name: STUNNEL_CLIENT_VERIFY_HOST
              value: "false"
            - name: STUNNEL_CLIENT_VERIFY_PEER
              value: "false"
            - name: STUNNEL_SERVER_REQUIRE_TLS
              value: "false"
            - name: STUNNEL_SERVER_VERIFY_CHAIN
              value: "false"
            - name: STUNNEL_SERVER_VERIFY_HOST
              value: "false"
            - name: STUNNEL_SERVER_VERIFY_PEER
              value: "false"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: pa-cacerts
              mountPath: /run/config
            - name: pa-tls-cert
              mountPath: /run/secrets/paw/tls-cert
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.mysqlData.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.mysqlData.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.mysqlData.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.mysqlData.livenessProbeTimeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.mysqlData.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.mysqlData.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.mysqlData.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.mysqlData.readinessProbeTimeoutSeconds }}
        - name: mysql-data1
          image: {{ .Values.docker_registry_prefix }}/mysql-cluster:2.0.170-ubi8
          args: ["ndbd"]          
          ports:
            - containerPort: 2201
              protocol: TCP
          resources:
            limits:
              cpu: "{{ .Values.mysqlData.cpuLimit }}"
              memory: "{{ .Values.mysqlData.memoryLimit }}"
            requests:
              cpu: "{{ .Values.mysqlData.cpuRequestLimit }}"
              memory: "{{ .Values.mysqlData.memoryRequestLimit }}"
          env:
            - name: HOSTNAMES
              value: "mysql-data1{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }} mysql-data2{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }} mysql-mgmt{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}"
            - name: READINESS_PORT
              value: "31001"
            - name: ENABLE_SSL
              value: "true"
            - name: SIDECAR_NAME
              value: "mysql-data1-stunnel"
            - name: SIDECAR_PORTS
              value: "1186,12201,2202"
            - name: SIDECAR_EXTRA_WAIT
              value: "5"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: mysql-data1-storage
              mountPath: /var/lib/mysql
              subPath: mysql-data1.1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.mysqlData.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.mysqlData.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.mysqlData.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.mysqlData.livenessProbeTimeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - date
            failureThreshold: {{ .Values.mysqlData.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.mysqlData.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.mysqlData.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.mysqlData.readinessProbeTimeoutSeconds }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: {{ .Values.persistence.podScheduler }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

