apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: prism-proxy{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: prism-proxy{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.prismProxy.replicas }}
  selector:
    matchLabels:
      name: prism-proxy{{ .Values.instanceIdWithinNamespace }}
  template:
    metadata:
      annotations:
        hook.activate.cpd.ibm.com/command: '[]'
        hook.deactivate.cpd.ibm.com/command: '[]'      
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: prism-proxy{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "3.0.10513-ubi8"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: 
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - prism-proxy{{ .Values.instanceIdWithinNamespace }}
              topologyKey: kubernetes.io/paw
      containers:
        - name: prism-proxy
          image: {{ .Values.docker_registry_prefix }}/prism-proxy:3.0.10513-ubi8
          ports:
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
          env:
            - name: PrismAdminServerLocation
              value: "http://prism-platform{{ .Values.instanceIdWithinNamespace }}:9080"
            - name: PrismAppServerLocation
              value: "http://prism-app{{ .Values.instanceIdWithinNamespace }}:9600"
            - name: PrismGridServiceLocation
              value: "http://prism-platform{{ .Values.instanceIdWithinNamespace }}:9080"
            - name: PrismPlatformLocation
              value: "http://prism-platform{{ .Values.instanceIdWithinNamespace }}:9080"
            - name: ProxyTimeoutSeconds
              value: "{{ .Values.common.proxyTimeoutSeconds }}"
          resources:
            limits:
              cpu: "{{ .Values.prismProxy.cpuLimit }}"
              memory: "{{ .Values.prismProxy.memoryLimit }}"
            requests:
              cpu: "{{ .Values.prismProxy.cpuRequestLimit }}"
              memory: "{{ .Values.prismProxy.memoryRequestLimit }}"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /proxyhealth
              port: 9090
            failureThreshold: {{ .Values.prismProxy.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.prismProxy.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.prismProxy.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.prismProxy.livenessProbeTimeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /proxyhealth
              port: 9090
            failureThreshold: {{ .Values.prismProxy.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.prismProxy.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.prismProxy.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.prismProxy.readinessProbeTimeoutSeconds }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

