apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: share-platform{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: share-platform{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.sharePlatform.replicas }}
  selector:
    matchLabels:
      name: share-platform{{ .Values.instanceIdWithinNamespace }}
  template:
    metadata:
      annotations:
        hook.activate.cpd.ibm.com/command: '[]'
        hook.deactivate.cpd.ibm.com/command: '[]'        
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: share-platform{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "1.0.384-ubi8"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: 
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - share-platform{{ .Values.instanceIdWithinNamespace }}
              topologyKey: kubernetes.io/paw
      containers:
        - name: share-platform
          image: {{ .Values.docker_registry_prefix }}/share-platform:1.0.384-ubi8
          ports:
            - containerPort: 9110
              protocol: TCP
          env:
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 9110
            failureThreshold: {{ .Values.sharePlatform.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.sharePlatform.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.sharePlatform.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.sharePlatform.livenessProbeTimeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.sharePlatform.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.sharePlatform.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.sharePlatform.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.sharePlatform.readinessProbeTimeoutSeconds }}
            httpGet:
              path: /healthcheck
              port: 9110
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

