apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: cdn{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: cdn{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.cdn.replicas }}
  selector:
    matchLabels:
      name: cdn{{ .Values.instanceIdWithinNamespace }}
  template:
    metadata:
      annotations:
        hook.activate.cpd.ibm.com/command: '[]'
        hook.deactivate.cpd.ibm.com/command: '[]'       
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: cdn{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "3.0.7096-ubi8"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: 
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - cdn{{ .Values.instanceIdWithinNamespace }}
              topologyKey: kubernetes.io/paw
      containers:
        - name: cdn
          image: {{ .Values.docker_registry_prefix }}/pa-cdn:3.0.7096-ubi8
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          resources:
            limits:
              cpu: "{{ .Values.cdn.cpuLimit }}"
              memory: "{{ .Values.cdn.memoryLimit }}"
            requests:
              cpu: "{{ .Values.cdn.cpuRequestLimit }}"
              memory: "{{ .Values.cdn.memoryRequestLimit }}"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            failureThreshold: {{ .Values.cdn.livenessProbeFailureThreshold }}
            initialDelaySeconds:  {{ .Values.cdn.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.cdn.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.cdn.livenessProbeTimeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            failureThreshold: {{ .Values.cdn.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.cdn.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.cdn.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.cdn.readinessProbeTimeoutSeconds }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

