apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: pa-content{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
  name: pa-content{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.paContent.replicas }}
  selector:
    matchLabels:
      name: pa-content{{ .Values.instanceIdWithinNamespace }}
  template:
    metadata:
      annotations:
        hook.activate.cpd.ibm.com/command: '[]'
        hook.deactivate.cpd.ibm.com/command: '[]'         
        productName: IBM Planning Analytics Workspace
        productID: com.ibm.ba.paw.{{ .Release.Name }}
        productVersion: {{ .Release.Name }}
      labels:
        app: {{ .Values.common.appName }}
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: pa-content{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "1.0.273-ubi8"
        pa-cacerts-version: {{ .Values.secrets.cacertVersion }}
        pa-tls-version: {{ .Values.secrets.tlsCertVersion }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: 
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - pa-content{{ .Values.instanceIdWithinNamespace }}
              topologyKey: kubernetes.io/paw
      volumes:
        - name: pa-cacerts
          emptyDir:
            medium: {{ .Values.secrets.tlsEmptyDirMedium }}
            sizeLimit: {{ .Values.secrets.tlsEmptyDirSizeLimit }}
        - name: pa-tls-cacerts
          secret:
            secretName: pa-tls-cacerts{{ .Values.instanceIdWithinNamespace }}
        - name: pa-tls-cert
          secret:
            secretName: {{ .Values.secrets.tlsCertSecretName }}{{ .Values.instanceIdWithinNamespace }}
      initContainers:
        - name: prepare-cacerts
          image: {{ .Values.docker_registry_prefix }}/k8s-config:1.0.107-ubi8
          command: ["/bin/bash"]
          args: ["-c", "/opt/harmony/start.sh capem"]
          env:
           - name: PA_KUBE_TM1_CA_CERTS
             value: /run/secrets/paw/tls-cacerts/cacerts.pem
           - name: PA_KUBE_TLS_CA_CERT
             value: /run/secrets/paw/tls-cert/{{ .Values.secrets.tlsCaCertName }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: {{ .Values.secrets.cpuLimit }}
              memory: {{ .Values.secrets.memoryLimit }}
            requests:
              cpu: {{ .Values.secrets.cpuRequestLimit }}
              memory: {{ .Values.secrets.memoryRequestLimit }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: pa-cacerts
            mountPath: /run/config
          - name: pa-tls-cacerts
            mountPath: /run/secrets/paw/tls-cacerts
          - name: pa-tls-cert
            mountPath: /run/secrets/paw/tls-cert
      containers:
        - name: pa-content
          image: {{ .Values.docker_registry_prefix }}/pa-content-service:1.0.273-ubi8
          ports:
            - containerPort: 9191
              protocol: TCP
          env:                        
            - name: REDIS_SENTINEL
              value: "{ \"name\": \"redis-cluster{{ .Values.instanceIdWithinNamespace }}\", \"sentinels\": [{ \"host\": \"sentinel1{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}\", \"port\": 26379 }, { \"host\": \"sentinel2{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}\", \"port\": 26379 }, { \"host\": \"sentinel3{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}\", \"port\": 26379 }], \"tls\": true }"
            - name: SSL_CA_BUNDLE_FILE
              value: "/run/config/cacerts.pem"
          resources:
            limits:
              cpu: "{{ .Values.paContent.cpuLimit }}"
              memory: "{{ .Values.paContent.memoryLimit }}"
            requests:
              cpu: "{{ .Values.paContent.cpuRequestLimit }}"
              memory: "{{ .Values.paContent.memoryRequestLimit }}"
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: pa-cacerts
              mountPath: /run/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 9191
            failureThreshold: {{ .Values.paContent.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.paContent.livenessProbeDelaySeconds }}
            periodSeconds: {{ .Values.paContent.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.paContent.livenessProbeTimeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 9191
            failureThreshold: {{ .Values.paContent.readinessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.paContent.readinessProbeDelaySeconds }}
            periodSeconds: {{ .Values.paContent.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.paContent.readinessProbeTimeoutSeconds }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

