apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  name: pa-registry-secret{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkZWZhdWx0LXJvdXRlLW9wZW5zaGlmdC1pbWFnZS1yZWdpc3RyeS5hcHBzLmlibXBlcHJlc3RvcmVjbHVzdGVyLmNlbnRyYWx1cy5hcm9hcHAuaW8iOnsidXNlcm5hbWUiOiJkZWZhdWx0IiwicGFzc3dvcmQiOiIiLCJlbWFpbCI6IiIsImF1dGgiOiJaR1ZtWVhWc2REb0sifX19Cg==

