apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ .Values.common.appName }}
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  name: pa-config-secret{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - secrets
  resourceNames:
  - pa-cookie-key{{ .Values.instanceIdWithinNamespace }}
  - pa-credential-store-key{{ .Values.instanceIdWithinNamespace }}
  - pa-gateway-cert{{ .Values.instanceIdWithinNamespace }}
  - pa-java-truststore-credential{{ .Values.instanceIdWithinNamespace }}
  - {{ .Values.secrets.ingressCertSecretName }}{{ .Values.instanceIdWithinNamespace }}
  - pa-couchdb-credentials{{ .Values.instanceIdWithinNamespace }}
  - pa-mongo-credentials{{ .Values.instanceIdWithinNamespace }}
  - pa-mysql-credentials{{ .Values.instanceIdWithinNamespace }}
  - pa-redis-credentials{{ .Values.instanceIdWithinNamespace }}
  - {{ .Values.secrets.tlsCertSecretName }}{{ .Values.instanceIdWithinNamespace }}
  - pa-tls-cacerts{{ .Values.instanceIdWithinNamespace }}
  verbs:
  - delete
  - get

